### ISSUE TITLE
writing avro in multi-process (pm2)

### ISSUE THREAD

**Issue by sparzan** [mtth/avsc#104]
Are there any good practices to starting an avro file in pm2 cluster-mode and appending it with writes through n different processes?

**Comment by mtth** [comment]
Nothing yet that I'm aware of. They should be similar to any concurrent writing using `pm2`.

If I had to recommend a solution, I'd advise you to have each process to write to its own file (or rotating set of files). If you also need to aggregate them into a single file, I'd implement this as a separate process which periodically streams through and merges them.

**Comment by sparzan** [comment]
i thought this would be easy as my bunyan implementation of log files, where all processes write to the same file and Linux logrotate copy and truncate that file while the app continues to write to the same location. 

it seems avsc is different and requires both a Metadata write first and a stream end to close the file (otherwise i get a corrupted avro). 

pm2 is currently managing a 32 processes cluster per machine with 3 machines. that's a lot of files to rotate every 5 minutes and later process,  thus I'm thinking about a better solution.

**Comment by mtth** [comment]
So two fundamental design choices of [Avro container files](https://avro.apache.org/docs/current/spec.html#Object+Container+Files) (what each `BlockEncoder` produces) make this particular use-case tricky:

+ As you mention, each container file requires a header. This doesn't work well with standard tools like `logrotate`'s `copytruncate` since a header has to be prepended each time the file is changed.
+ Files are written in compressed blocks rather than in individual record chunks. This works great for single-process writes (enabling built-in compression for example) but not for concurrent appends since each block will typically be too large to guarantee [atomic operations](http://stackoverflow.com/q/1154446/1062617).

There might be workarounds if we use a different storage format, header/block-less. I'm not familiar with `bunyan` but it looks like it'd be possible to implement a custom stream which'd handle rotations appropriately (probably combined with a custom [`reopenFileStreams`](https://github.com/trentm/node-bunyan/blob/40ee2503cce50b8259c1124d7dbe0e7f7ee689c1/lib/bunyan.js#L710))

What are the main benefits you're hoping to get from switching to Avro from JSON logging?

**Comment by sparzan** [comment]
thanks @mtth, i think the concurrency problem will outweigh the benefits of avro in this case. i'll go with compressed json instead. thanks for this great module.

**Comment by ronaldocpontes** [comment]
Hey @sparzan.

I am currently using https://github.com/mtth/avsc/pull/101 createFileAppender to logrotate inside the App. It also has some other features that are useful serverside.
