### ISSUE TITLE
Any way to use this without a file?

### ISSUE THREAD

**Issue by boompig** [mtth/avsc#107]
If I have a string or buffer representing an Avro file, is there a method I can pass that to, or do I have to create a file on disk?

**Comment by boompig** [comment]
Same question but for writing.

I see it's implemented using `fs.createReadStream ` and `fs.createWriteStream`, but it doesn't look like you can pass the arguments from `createFileDecoder` into the above calls, since their arguments do not depend on those parameters. I was thinking the `fd` parameter looked promising.

Possibly I am overlooking something simple here?

**Comment by mtth** [comment]
You don't have to create a file. `createFile{De,En}coder` are thin wrappers around their duplex-stream equivalents (for example, [`BlockDecoder`](https://github.com/mtth/avsc/wiki/API#class-blockdecoderopts)).

You could call these directly after creating a stream from your buffer or string. This last step is straightforward; it looks like there are a few libraries out there that might help, otherwise it's simple enough to do yourself:

```javascript
const stream = require('stream');

/** Transform a buffer into a readable stream. */
function asReadableStream(buf) {
  const bufs = [buf];
  return new stream.Readable({
    read() { this.push(bufs.pop() || null); }
  });
}

// Sample usage.
const buf; // Your buffer.
asReadableStream(buf)
  .pipe(new avro.streams.BlockDecoder())
  .on('data', function (val) { console.log(val); });
```

Similarly for writing. Does this answer your question?

**Comment by mtth** [comment]
I'm guessing you were able to get this to work; feel free to reopen if not.

**Comment by paulocoghi** [comment]
Excellent information! Thanks, @mtth !
