### ISSUE TITLE
AVRO support to translate Float-Exceptions to DBnull

### ISSUE THREAD

**Issue by christian2345** [mtth/avsc#154]
Hi Matt,

your previous suggestions made me a happy user ;-)  So far so good.
I am wondering if you would have a suggestion how to cope with yet another issue.

Some databases (e.g. AWS Redshift) are unable to cope with floating point exceptions (NaN varieties, +inf, -inf). For a CSV ingest, there is a specific attribute "NULL as ..." to interprete certain stringes as DBnull, allowing for special treatment of e.g. NaN. However, this option does not exist with AVRO import.

Therefore, my question: is the package already capable of transforming a valid floating point exception (eg NaN) on input into NULL in the encoded output stream? 
If not, would you consider adding this option summarily for all floarting point exceptions?

I would hope we can handle the issue that way. The AWS forum has not found a workaround over the last 6 months....

best regards
Chris

**Comment by mtth** [comment]
Hi @christian2345, it depends on how you import the data into AWS. If you import decoded values, we can easily write a [logical type](https://github.com/mtth/avsc/wiki/Advanced-usage#logical-types) to transform certain float values to `null`. If you import encoded values (e.g. Avro-encoded container files), our options aren't as great since we have no control on how the values are decoded inside AWS. Here are two suggestions:

+ Changing the schema of the affected float fields to unions `['null', 'float']`, such that `null` has a valid encoding and the data can be imported as-is. This would be straightforward to do automatically by overriding the `'float'` key in the `registry` option when instantiating a type (and using the type's `schema()` when importing instead of the original one).
+ Using a float sentinel value to represent all unsupported float values. This might work if you can use properties of your data to guarantee that the sentinel will never occur otherwise (for example using `-1` if all your data is non-negative). You could also use a post-processing step to transform the sentinel value into a less magical `null`.

Does either sound applicable to your use-case?
