### ISSUE TITLE
Serialize message ommiting 'optional' value crash

### ISSUE THREAD

**Issue by VBolduc-TM** [mtth/avsc#163]
Hello!

First of all, congratulation for the great work and I would like to apolozige because I'm really starting with Avro/Schema registry and all that stuff.

I was trying to apply the quick start guide from the Apache Avro documentation (https://avro.apache.org/docs/1.8.1/gettingstartedpython.html) to have an example of Avro schema to start with.

When I try to serialize a message that ommits a field that has a type `["string", "null"]`, the library is throwing me an error.
In my snippet, the field is 'favorite_color'. It seems that "null" is not an acceptable value for this field. I also tried with 'undefined' instead of null and it crash on the parsing of the schema (which make sense).

I tried the basic example with the Python library and it works fine. I can provide the source code if requested.
Here is the Javascript code containing the schema and the message: https://gist.github.com/VBolduc-TM/3e57905e183733fa21be064a1bcf82cf

Am I doing something wrong?
Thank you!

**Comment by mtth** [comment]
Hey @VBolduc-TM! Thanks for the detailed explanation and example, you're almost there: you just needed to add a default to your type definition (and switch the order of the types in the union since [defaults should always be of the type of the first branch](https://avro.apache.org/docs/1.8.2/spec.html#schema_record)):

```javascript
const schema = {
  "namespace": "example.avro",
  "type": "record",
  "name": "User",
  "fields": [
     {"name": "name", "type": "string"},
     {"name": "favorite_number",  "type": ["int", "null"]},
     {"name": "favorite_color", "type": ["null", "string"], "default": null} // <-
  ]
 };
```

The field was otherwise nullable but not optional; take a look at https://github.com/mtth/avsc/issues/118 for more information. (It looks like the python implementation merges the two concepts but they are best kept separate.)

**Comment by VBolduc-TM** [comment]
Sorry for the late reply.
I followed your sugestion and it worked, Thank you!

Being more familiar with Python and Java, I didn't thought of the differences between null and undefined. Make a lot of sense now!
