### ISSUE TITLE
Serializing with alternatives

### ISSUE THREAD

**Issue by bali182** [mtth/avsc#179]
I'm trying to serialize an object with a field that has multiple type alternatives. A simplified example:

```js
const schemaJSON = {
  type: "record",
  name: "Root",
  fields: [{
    name: "child",
    type: [
      "null",
      {
        name: "Cat",
        type: "record",
        fields: [
          {
            name: "meow",
            type: "string"
          },
          {
            name: "scratch",
            type: "string"
          }
        ]
      },
      {
        name: "Dog",
        type: "record",
        fields: [
          {
            name: "bork",
            type: "string"
          },
          {
            name: "color",
            type: "string"
          }
        ]
      }
    ],
  }]
}

// For all intents and purposes this is supposed to match a Root type with a Dog child
const example = {
  child: {
    bork: 'hi',
    color: 'red'
  }
}

const avsc = require('avsc')
const schema = avsc.Type.forSchema(schemaJSON)
const buffer = schema.toBuffer(example)
```

This gives me an error: `Error: invalid ["null","Cat","Dog"]: {"bork":"hi","color":"bork"}`

Is my schema incorrect? In case it is how would I express the `Root` type in this context:

```ts
interface Animal { }
class Dog implements Animal {
  bork: string
  color: string
}
class Cat implements Animal {
  meow: string
  scratch: string
}
class Root {
  child?: Animal
}
```

In case it isn't I'd like to report a bug 🐛

**Comment by mtth** [comment]
Since your union contains multiple records, it's represented in-memory as a [`WrappedUnion`](https://github.com/mtth/avsc/wiki/API#class-wrappeduniontypeschema-opts). The simplest change you can do to make it work is to wrap the child nodes:

```js
const example = {
  child: {
    Dog: { // Include the selected type here.
      bork: 'hi',
      color: 'red'
    }
  }
}
```

If this is inconvenient, you can implement a custom [logical type](https://github.com/mtth/avsc/wiki/Advanced-usage#logical-types) which will do the branch inference logic for you. https://github.com/mtth/avsc/issues/174 has some more context which might also be helpful.

**Comment by bali182** [comment]
@mtth cheers, thanks for the help!
