### ISSUE TITLE
Node 0.11 requirement

### ISSUE THREAD

**Issue by jadbox** [mtth/avsc#18]
Please explain why specifically Node 0.11 is required. I'm curious if Node v4.2 will work alternatively?

**Comment by mtth** [comment]
A version of node *greater or equal to* `0.11` is required because of breaking changes to [buffers](https://github.com/nodejs/node/blob/master/CHANGELOG.md#buffer) and [streams](https://github.com/nodejs/node/blob/master/CHANGELOG.md#streams) in that release (which greatly improve both APIs). `avsc` is actually tested on all major releases since then, including [`4.2`](https://travis-ci.org/mtth/avsc/jobs/93709300) which you mention.
