### ISSUE TITLE
Schema does not get saved in the serialized file

### ISSUE THREAD

**Issue by prateekkohli2112** [mtth/avsc#180]
Hi,

I am trying to write serialized data to a file, but it does not store the schema with the data (as it does in AVRO Java API).

I am using the below code:

var buf = type.toBuffer({"Activities": nodesMap, "edges": saveEdges, "javaCode": code});
var blob = new Blob([buf], {type: "text/plain;charset=utf-8"});
window.saveAs(blob, "mydag.json");

The file which is getting generated has the serialized object written, but it does not have the schema associated with it (Usually avro appends serialized data after the schema only).

Do I need to use any other API function to save the schema before the object.

I am doing this using browserify.

Thanks

**Comment by mtth** [comment]
`toBuffer` serializes a single value; if you meant to encode values in an [object container file](https://avro.apache.org/docs/1.8.2/spec.html#Object+Container+Files) (which includes the schema in its header), you should use a [`BlockEncoder`](https://github.com/mtth/avsc/wiki/API#class-blockencoderschema-opts). The convenience [`createBlobEncoder`](https://github.com/mtth/avsc/wiki/API#createblobencoderschema-opts) function might be helpful for you since you're using Browserify.

**Comment by mtth** [comment]
The blob will be the stream's single readable value. You can extract it for example as follows:

```js
const encoder = avro.createBlobEncoder(type)
  .on('data', (blob) => {
    // This function will get called with the fully built blob once the stream ends.
  });

encoder.write(foo);
encoder.write(bar);
encoder.end(); // Trigger the blob callback.
```

**Comment by prateekkohli2112** [comment]
Thanks !!
