### ISSUE TITLE
Question about the HTTP transport example

### ISSUE THREAD

**Issue by bali182** [mtth/avsc#184]
I'm trying to get the HTTP transport example working. Looking at the following snippet, what exactly should respond to the HTTP requests?

While debugging I can see that the endpoint is hit, the channel is created, but the client doesn't get a response (request times out).

```js
http.createServer()
  .on('request', function (req, res) {
    server.createChannel(function (cb) { cb(null, res); return req; });
  })
  .listen(8080);
```

Also, thanks for the quick responses for the noob questions :)

**Comment by mtth** [comment]
Hey @bali182, that's odd. Can you share your client code? I just ran the [HTTP transport example](https://github.com/mtth/avsc/wiki/Quickstart#calling-our-service) from the Wiki and the responses go through.

> Looking at the following snippet, what exactly should respond to the HTTP requests?

The server will write its response to `res` after the service has handled it.

**Comment by bali182** [comment]
Sure I'll create a mini repo to reproduce what I'm seeing.

**Comment by mtth** [comment]
Thank you for the great setup and README! The issue is that [buffering](https://github.com/mtth/avsc/wiki/API#servicecreateclientopts) isn't enabled in the RPC client; this causes a "no active channels" error when the message is sent. Simply setting the option when [creating your client](https://github.com/bali182/avro-test/blob/d840cc3578168d192dfd9524c6de459baa3cab5f/src/client.js#L14) does the trick and we're able to see your server's response:

```js
const client = service.createClient({transport, buffering: true}) 
```

Alternatively, you could wait until the channel is ready to send requests:

```js
client.once('channel', () => {
  // The channel is ready now.
  client.getSampleItem({ name: 'ImASample' }, (error, item) => {
    console.log(error, item)
  })
})
```

**Comment by bali182** [comment]
Amazing thanks very much! I'm going to keep the repo there so if someone hits this issue, the conversation stays relevant.

**Comment by mtth** [comment]
Happy to help. BTW, since it looks like you're using webpack, `avsc` has a [custom loader](https://github.com/mtth/avro-webpack-loader) for `.avdl` files which could simplify your client code.
