### ISSUE TITLE
Recursive map schemas

### ISSUE THREAD

**Issue by princjef** [mtth/avsc#191]
Thanks for the great library! It's been able to take everything I throw at it so far 😄 

I'm running into an issue now with trying to define recursive schemas. I have a use case where i need to be able to represent a JSON object which can have arbitrary keys and be of arbitrary depth. My thinking was to define something like this:

```js
const recursiveMapType = avro.Type.forSchema({
    name: 'RecursiveMap',
    type: 'map',
    values: [
        'string',
        'double',
        'boolean',
        'RecursiveMap'
    ]
});
```

However, this leads to an `Error: undefined type name: RecursiveMap` (using version 5.3.1).

When I try to define a similar recursive structure based on a record instead of a map, it works fine:

```js
const recursiveRecordType = avro.Type.forSchema({
    name: 'RecursiveRecord',
    type: 'record',
    fields: [
        {
            name: 'foo',
            type: [
                'string',
                'double',
                'boolean',
                'RecursiveRecord'
            ]
        }
    ]
});
```

Is there something about the Avro map type that prevents doing recursive maps in this way? I'm no Avro expert so it's entirely possible I'm trying to do something invalid here.

**Comment by mtth** [comment]
[Maps](https://avro.apache.org/docs/1.8.2/spec.html#Maps) aren't a [_named type_](https://avro.apache.org/docs/1.8.2/spec.html#names) according to the Avro specification unfortunately, so they can't be referenced recursively (in your example, the `name` field is ignored which triggers the error you see).

The simplest way to work around this is to "box" your map inside a record with a single field. This works since [records](https://avro.apache.org/docs/1.8.2/spec.html#schema_record) are a named type; however your data representation becomes less convenient, you'll need to box/unbox values manually.

```js
const type = avro.Type.forSchema({
    name: 'RecursiveMap',
    type: 'record',
    fields: [
      {
        name: 'unboxed', // The record's single field.
        type: {
          type: 'map',
          values: [
              'string',
              'double',
              'boolean',
              'RecursiveMap'
          ]
        }
      }
    ]
});

type.isValid({unboxed: {foo: 'one', bar: {unboxed: {baz: 2}}}}); // A sample valid value.
```

By adding a [`LogicalType`](https://github.com/mtth/avsc/wiki/Advanced-usage#logical-types), you can have `avsc` do the boxing/unboxing transparently. For example, the logical type in the snippet below will let you keep the exact same representation you had initially:

```js
/** A basic logical type to automatically "unwrap" values. */
class BoxType extends avro.types.LogicalType {
  _fromValue(val) { return val.unboxed; }
  _toValue(any) { return {unboxed: any}; }
}

const type = avro.Type.forSchema({
    name: 'RecursiveMap',
    type: 'record',
    logicalType: 'box', // Our logical type.
    fields: [
      {
        name: 'unboxed',
        type: {
          type: 'map',
          values: [
              'string',
              'double',
              'boolean',
              'RecursiveMap'
          ]
        }
      }
    ]
}, {logicalTypes: {box: BoxType}});

type.isValid({foo: 'one', bar: {baz: 2}}); // Valid without explicit boxing!
```

(You'll need to upgrade to `5.4.0` for this last snippet to work.)

**Comment by princjef** [comment]
Ah okay. I had seen talk of unions not being named but I didn't realize the same was true of maps. In that case this makes sense. Thanks for the information!

For purposes of being able to serialize/deserialize the data i think both of the solutions you mention make sense (the LogicalType one is particularly elegant). Ideally the representation in Avro would be able to deserialize across different languages/libraries into the desired JSON automatically, but that doesn't seem possible based on what you've described.

I'll have to go back and decide how I want to handle this case but regardless it sounds like this is an artifact of Avro itself rather than the library, so I'll close the issue. Thanks for the insights! 😃
