### ISSUE TITLE
Issue with complex types union

### ISSUE THREAD

**Issue by fredfort** [mtth/avsc#197]
Hello, 
Thank you for this library!
I have an issue when I try to create a union type with complex objects.
Here is the schema:

```
{
  "type": "record",
  "name": "Person",
  "fields": [
    {
      "name": "fullName",
      "type": {
        "name":"FullName",
        "type": "record",
        "fields": [
          {
            "name": "firstname",
            "type": "string"
          },
          {
            "name": "lastname",
            "type": "string"
          }
        ]
      }
    },
    {
      "name": "address",
      "type": {
        "name":"Address",
        "type": "record",
        "fields": [
          {
            "name": "city",
            "type": "string"
          },
          {
            "name": "country",
            "type": "string"
          }
        ]
      }
    },
    {
      "name":"extra",
      "type":[
        "string",
        "Address",
        "FullName"
      ]
    }
  ]
}
```

And here the actual JSON: 

```
{
  "fullName":{
    "firstname":"John",
    "lastname":"Doe"
  },
  "address":{
    "city":"Dublin",
    "country":"Ireland"
  },
  "extra": "test"
}
```

For some reasons the following code is failing:

```
const avro = require("avsc");
// schema is equal to the first object pasted above
// example is equal to the second object pasted above
const type = avro.Type.forSchema(schema);
const buf = type.toBuffer(example);
```

I get the following error when the `toBuffer` method is called
```
Error: invalid ["string","Address","FullName"]: "test"
```

I thought that the value "test" would be valid as the union is supposed to accept "string".

NB: This example is working fine if the union is made of primitive type like 
```
 type":[
        "string",
        "int",
        "null"
 ]
```

Any thoughts?

Thank you, 

Fred

**Comment by mtth** [comment]
Hey @fredfort. This is because a union with multiple records falls back to a [`WrappedUnion`](https://github.com/mtth/avsc/wiki/API#class-wrappeduniontypeschema-opts), while your later example can use the simpler [`UnwrappedUnion`](https://github.com/mtth/avsc/wiki/API#class-unwrappeduniontypeschema-opts) alternative. Concretely, this means that you'll need to "wrap" the string in your example:

```js
{
  "fullName":{
    "firstname":"John",
    "lastname":"Doe"
  },
  "address":{
    "city":"Dublin",
    "country":"Ireland"
  },
  "extra": {
    "string": "test" // Note the "string" key here.
  }
}
```
Likewise, if you wanted to have an address `extra` field:
```js
{
  "fullName":{
    "firstname":"John",
    "lastname":"Doe"
  },
  "address":{
    "city":"Dublin",
    "country":"Ireland"
  },
  "extra": {
    "Address": { // "Address" key here, matching the value's type's name.
      "city": "Galway",
      "country": "Ireland"
    }
  }
}
```
The API links above have a little more information and motivation around why this is necessary (see also [`Type.forSchema`](https://github.com/mtth/avsc/wiki/API#typeforschemaschema-opts)'s `wrapUnions` option which controls this wrapping). Let me know if anything is still unclear.

**Comment by fredfort** [comment]
Thank you very much for your clear and quick response.
That's fix my issue.

Thanks, 

Fred
