### ISSUE TITLE
avsc.parse() lost some configuration of type

### ISSUE THREAD

**Issue by xkuqi** [mtth/avsc#23]
I use avro-1.7.7 java api to create test.avsc like:
{
     "type" : "record",
     "name" : "SimplePOJO",
     "namespace" : "avro.test",
     "fields" : [ 
      {
            "name" : "timestamp",
            "type" : {
                       "type" : "long",
                       "CustomEncoding" : "DateAsLongEncoding"
                        }
      }
]
}

when i use avsc in nodejs:

var type = avsc.parse('./test.avsc');

it lost the infomation of "CustomEncoding", can i get the origin(full information) avsc (generate by java) by the project?

**Comment by mtth** [comment]
It depends.

If you'd simply like to keep the schema as-is (but not do anything with it), then you should use (for example) `fs.readFileSync` and `JSON.parse` and keep a reference to that schema:

```javascript
var fs = require('fs');

var schema = JSON.parse(fs.readFileSync('./test.avsc')); // The complete schema.
var type = avsc.parse(schema); // If you'd also like the type.
```

(Types do not keep a reference to the schema that created them since that would either introduce consistency issues or require a deep-copy of arbitrary objects.)

If you'd like to introduce custom behavior from these non-standard fields (for example automatically transforming your `long` above into a JavaScript `Date`), you can use [logical types](https://github.com/mtth/avsc/wiki/API#class-logicaltypeattrs-opts-types). There is actually an example very similar to your use-case [here](https://github.com/mtth/avsc/wiki/Advanced-usage#logical-types).
