### ISSUE TITLE
performance and benchmarks

### ISSUE THREAD

**Issue by jfromaniello** [mtth/avsc#24]
First your benchmark looks way solid, you have done a great job.

I am curious about the JSON comparison in your benchmark, doing a simple test like this:

```javascript
var avsc = require('avsc');

var type = avsc.parse({
  name: 'Request',
  type: 'record',
  fields: [
    {name: 'id', type: 'string' },
    {name: 'method', type: 'string'},
  ]
});

var start = new Date();

for (var i = 0; i <= 1000000; i++) {
  type.fromBuffer(type.toBuffer({ id: i.toString(), method: 'PING' }));
}

console.log('finished in', new Date() - start);
```

versus

```javascript
var start = new Date();

for (var i = 0; i <= 1000000; i++) {
  JSON.parse(JSON.stringify({ id: i.toString(), method: 'PING' }));
}

console.log('finished in', new Date() - start);
```

I do not get the **twice as fast than JSON** highlighted in your README but rather this:

```
/tmp/test-avro » node test-json.js
finished in 1264
/tmp/test-avro » node test-avsc.js
finished in 1942
```

**Comment by mtth** [comment]
Encoding and decoding rates for each library will vary per schema (`avsc` is *typically* twice as fast, i.e. often but not always). In particular, JSON is exceptionally good at encoding strings, so your benchmark is extremely friendly towards it. JSON relative performance will degrade rapidly as you add other types.

For example just substituting one of the strings for an integer (by changing `i.toString()` to `i`) yields:
```
finished in 1028 # avsc
finished in 1096 # JSON
```

Using an `enum` instead of a string for `method` will yield:
```﻿
finished in 640 # avsc
﻿finished in 1061 # JSON
```

If you are curious, you can take a look at [this table](https://github.com/mtth/avsc/wiki/Benchmarks#various-schemas-and-implementations) which shows throughput rates for 15 different schemas (all available in `etc/benchmarks/schemas`). The results for `ArrayString.avsc` show the strength of JSON encoding for strings (note that this isn't however the case when decoding!).

Ps: It seems to be working fine in this example, but in general micro-benchmarks can be very misleading (e.g. some code-paths might be eliminated by v8). The scripts used to generate the numbers on the benchmarks page take extra care to making sure that doesn't happen, but this isn't the case in general.

**Comment by jfromaniello** [comment]
Thank you very much for your response, you are right.

> some code-paths might be eliminated by v8

I think there is a little of this on my test too. Using the same payload but doing two changes:

1- generate all strings at once in an array then parse all strings.
2- using some property of the parsed object

I got exactly what you advertise in the README:

```
/tmp/test-avro » node test-json.js
finished in 1091
/tmp/test-avro » node test-avsc.js
finished in 536
```

Awesome work!
