### ISSUE TITLE
Q: Performance improvement on decoding

### ISSUE THREAD

**Issue by michelde** [mtth/avsc#246]
Hi Matthieu,

I'm trying to get a Object Container Message decoded using the BlockDecoder. I'm happy to get it working, but I'm struggling with the performance. Probably, I'm using the decode not the right way? In my test it took over 2 seconds to decode 1000 messages. Is this an expected value or is there some way to improve my coding (e.g. creating the BlockDecoder just once?).

```javascript
const avro = require('avsc');
const EventAvroType = avro.parse({
    "name": "event",
    "type": "record",
    "fields": [
        {"name": "id", "type": "string"},
        {"name": "app", "type": "string"},
        {"name": "event", "type": "string"},
        {"name": "ip", "type": "string"},
        {"name": "dt", "type": "string"},
        {"name": "ts", "type": "long"},
        {"name": "user_id", "type": "string"}
    ]
});

const event = {
    id: 'bad482a7dd1471149879d840c10f50f6a43583dc',
    app: 'my_app',
    event: 'e2',
    ip: '192.168.0.1',
    dt: '2016-01-01T00:00:22-03:00',
    user_id: 'b0d21768-5d6c-11e6-8b77-86f30ca893d3',
    ts: 1451617222000 
};

// encode message
const encodeMessage = data => {
  let messageEncoded = '';
  return new Promise((resolve, reject) => {

    const avroEncoder = new avro.streams.BlockEncoder(EventAvroType);
    avroEncoder.on('data', (chunk => {
      messageEncoded += chunk.toString('hex');
    }))
    avroEncoder.on('error', (err) => {
      reject(err)
    })
    avroEncoder.write(data); // We're writing the event directly instead of a buffer.
    avroEncoder.end();
    avroEncoder.on('end', (() => {
      resolve(messageEncoded)
    }))
  })
}

const decodeMessage = buffer => {
  return new Promise((resolve, reject) => {
    let result;
    const blockDecoder2 = new avro.streams.BlockDecoder(); // The streaming decoder.
    blockDecoder2.on("data", val => {
      result = val;
    });
    blockDecoder2.on("end", () => {
      resolve(result)
    });
    blockDecoder2.on("error", err => {
      reject(err)
    });
    blockDecoder2.end(buffer);
  })
};

async function startSingleTest() {
  const encodedMessageHex = await encodeMessage(event);
  const message = await decodeMessage(Buffer.from(encodedMessageHex.toString(), "hex"));
  console.log(`Decoded message: ${message}`);
}

async function performanceTest(counter) {
  const encodedMessageHex = await encodeMessage(event);
  const encodedMessageBuffer = Buffer.from(encodedMessageHex.toString(), "hex")
  const startTime = new Date().getTime();
  for (let i = 0; i < counter; i+=1) {
    await decodeMessage(encodedMessageBuffer)
    if (i % 1000 === 0) {
      const used = process.memoryUsage().heapUsed / 1024 / 1024;
      console.log(`The script uses approximately ${Math.round(used * 100) / 100} MB`);
    }
  }
  console.log(`Processing time for ${counter} Records ${new Date().getTime() - startTime}`);
}

startSingleTest();
performanceTest(10000);
```

Any feedback are welcome.

Thanks Michel

**Comment by mtth** [comment]
Hi Michel. This is most likely because you are encoding a single record per container (each `BlockEncoder` produces a single [object container](http://avro.apache.org/docs/current/spec.html#Object+Container+Files)) and containers have significant overhead. Containers are meant to contain many records (often thousands or more) to obtain good compression and low overhead ratios.

Depending on your use-case, you could write more records to each `BlockEncoder` (e.g. if you are writing files for batch processing downstream) or simply encode each record directly using `toBuffer` (possibly prepending an ID to identify its schema, similar to what is often done when [streaming to Kafka](https://github.com/mtth/avsc/issues/22#issuecomment-166350702)). Either option should offer significantly improved performance.

**Comment by michelde** [comment]
Hi Matthieu,

thanks for your answer and providing ideas to solve the performance issue. Unfortunately I'm just a consumer on the kafka topic and can't influence the producing message. 
As I'm only dealing with a couple of different schemas I thought I could store the schema (event 'metadata') and pass the schema next time when creating the `BlockDecoder` as option `readerSchema`, to get the decoding improved. However, when passing the `readerSchema` to the `BlockDecoder` it takes even longer to decode the message. 

If you have another idea to improve the performance on decoding the object container file let me know. Otherwise we can close this question as answered. 

Thanks,
Michel

**Comment by mtth** [comment]
You might be able to get a speedup by using a custom [`parseHook` option](https://github.com/mtth/avsc/wiki/API#class-blockdecoderopts) to return cached types. Transforming a JSON schema into a `Type` can be an expensive operation, which you would then bypass.

I'll close this issue since I'm afraid there isn't much we else can do from the receiver side. If possible, I would encourage you to also reach out to the producing team: wrapping each record in a container file is excessive overhead and not an idiomatic use of Kafka.

**Comment by michelde** [comment]
Hi Matthieu,

just to confirm that your suggestion increased the performance about 6x. The first example took about 5200 ms to process for 50000 records and using the `parseHook` callback I'm able to process 50000 records in about 800ms. 

This is fast enough for my desired use case. 

Thanks,
Michel
