### ISSUE TITLE
Using multiple schemas in forSchema

### ISSUE THREAD

**Issue by nicholasmfsmith** [mtth/avsc#252]
Hi,

I'm trying to be able to use multiple schemas. My current schema structure is:
```javascript
const schemas = [
  {
    "type": "record",
    "name": "Inner",
    "fields": [
      {
        "name": "id",
        "type": "string"
      }
    ]
  },
  {
    "type": "record",
    "name": "Outer",
    "fields": [
      {
        "name": "test",
        "type": "string"
      },
      {
        "name": "testInner",
        "type": "Inner"
      }
    ]
  }
]

const message = {
    "test": "this is a test",
    "testInner": {
        "id": "this-is-an-id"
    }
}
```

Currently, when I run
```javascript
 const type = avro.Type.forSchema(schemas);
 const buffer = type.toBuffer(message);
```
it throws an invalid schema : val error coming from WrappedUnionType.protoype._write since keys.length does not equal 1.

Is it possible to use multiple schemas when they're not circular dependencies? If so, what is the best way to do this?

Thanks

Note: Referencing previous reply below

-------------------------------------------------------------------------------------------
Sure, you'll need to expand `B`'s schema the first time it's encountered. I think this'll do the trick:

```javascript
const type = avro.Type.forSchema([
            {
                "type": "record",
                "name": "A",
                "fields": [
                    {
                        "name": "fieldB",
                        "type": {
                          // Put B's schema here since it's the first time we encounter it.
                          "type": "record",
                          "name": "B",
                          "fields": [{"name": "fieldA", "type": "A"}]
                        }
                    }
                ]
            },
            "B" // Now we can just reference it by name.
        ]);
```

_Originally posted by @mtth in https://github.com/mtth/avsc/issues/32#issuecomment-373426472_

**Comment by mtth** [comment]
Hi. Since `schemas` is an array in your example, `type` ends up being a union (containing both `Inner` and `Outer`). However `message` is an instance of `Outer`, so `type.toBuffer(message)` correctly rejects it (unions of records are [wrapped](https://github.com/mtth/avsc/wiki/API#class-wrappeduniontypeschema-opts)).

The simplest way to fix this is to call `Type.forSchema` on `Outer`'s schema. Since there are no circular dependencies we can simply inline `Inner`'s schema inside it:

```javascript
const outerType = Type.forSchema({
    "type": "record",
    "name": "Outer",
    "fields": [
      {
        "name": "test",
        "type": "string"
      },
      {
        "name": "testInner",
        "type": { // Note the inlined schema here.
          "type": "record",
          "name": "Inner",
          "fields": [
            {
              "name": "id",
              "type": "string"
            }
          ]
        }
      }
    ]
  })
```

Alternatively, you can also access both types via an explicit `registry`:

```javascript
const registry = {}; // Registry where new types get added.
const unionType = Type.forSchema(schemas, {registry}); // Same as type in your example.
const outerType = registry.Outer;
const innerType = registry.Inner;
```

Which one is better will depend on whether you only ever need to access one type (in which case the former is simpler) or multiple (here having the latter's registry is handy).
