### ISSUE TITLE
Accessing the Avro.Schema from a reader

### ISSUE THREAD

**Issue by mattkirwan** [mtth/avsc#29]
Hi,
I feel like I'm struggling to understand a core concept in using this package and was hoping that I could be given a nudge in the right direction about what I may be missing. Apologies if this is not the correct place for this question.

I have a "Writer" which ultimately is responsible for putting an avro encoded message onto a Kafka message bus, here is a contrived example:

```javascript
/**********
 * WRITER *
 **********/
let schema = {
    type: "record",
    name: "User",
    fields: [
        {
            name: "firstname",
            type: "string"
        },
        {
            name: "surname",
            type: "string"
        }
    ],
}

let message = {
    'firstname': 'John',
    'surname': 'Smith'
}

let type = avro.parse(schema);

let sentBuffer = type.toBuffer(message);

/**********
 * KAFKA *
 **********/
// Send to Kafka
console.log("=====SENT BUFFER=====");
console.log(sentBuffer);
```

And on the other side of the Kafka cluster I have a "Reader" which needs to decode the message:

```javascript

/**********
 * READER *
 **********/
// Consume Kafka message
let receivedBuffer = new Buffer(sentBuffer);

console.log("=====RECEIVED BUFFER=====");
console.log(receivedBuffer.toString());
```

The above code outputs:

```bash
=====SENT BUFFER=====
<Buffer 08 4a 6f 68 6e 0a 53 6d 69 74 68>
=====RECEIVED BUFFER=====
John
Smith
```

As you can see the message buffer that is sent doesn't (seemingly) contain any Avro header/meta information (such as schema id/string etc...). I would expect these things through from my limited understanding of the Avro docs.

What am I missing? How do I decode a message using the schema that's meant to be inside my message (rather than depending on it again)?

Any help is greatly appreciated.

Kind regards,

Matt

**Comment by mtth** [comment]
Hey, no problem.

> As you can see the message buffer that is sent doesn't (seemingly) contain any Avro header/meta information (such as schema id/string etc...). I would expect these things through from my limited understanding of the Avro docs.

I'm guessing you're referring to [this section](https://avro.apache.org/docs/current/index.html#schemas) of Avro's documentation. The first paragraph can be a bit misleading, Avro actually only specifies that  the schema should be included with the records when writing [container files](https://avro.apache.org/docs/current/spec.html#Object+Container+Files) (and RPC, but that's another story). And this is a good thing since a schema can easily be larger than the encoded data it represents (so the overhead of including it inside each Kafka message would be prohibitive).

So it's left up to the client to decide how best to share schemas between readers and writers. If you can assume that your schema never changes (the simplest case), you don't have to include it at all in the messages. Otherwise a common approach is to prefix each message by a schema ID from which the full schema can be retrieved (this is what happens if you use Confluent's [schema registry](https://github.com/confluentinc/schema-registry), see https://github.com/mtth/avsc/issues/22 for more information on this).

Does this make sense?

**Comment by mattkirwan** [comment]
Hi mtth,

Perfect! That got me nudged onto the correct path and I've solved with the following (should anyone else google themselves here):

```javascript
'use strict';
let avsc = require('avsc');

function toMessageBuffer(val, type, schemaId, length) {
  let buf = new Buffer(length || 1024);
  buf[0] = 0; // Magic byte.
  buf.writeInt32BE(schemaId, 1);

  let pos = type.encode(val, buf, 5);
  if (pos < 0) {
    // The buffer was too short, we need to resize.
    // return getMessageBuffer(type, val, schemaId, length - pos);
  }
  return buf.slice(0, pos);
}

// This could be any source - each key being the Unique Schema ID
let schema = {
    '8': {},
    '9': {},
    '10': {},
    '11': {},
    '12': {
        type: "record",
        name: "User",
        fields: [
            {
                name: "firstname",
                type: "string"
            },
            {
                name: "surname",
                type: "string"
            }
        ],
    },
    '13': {},
    '14': {},
}

// Our message
let message = {
    'firstname': 'John',
    'surname': 'Smith'
}

// Create the type from the unique schema
let type = avsc.parse(schema[12]);

// Encode a new message - the 3rd param is the unique schema id
let bufferedMessage = toMessageBuffer(message, type, 12, 1024);

/****************
 *  ~KAFKA~  *
 ****************/

console.log("=====Received Message=====");
let readerType = avsc.parse(schema[bufferedMessage[4]]); // Let's parse this shit with our unique schema ID

// Decode our message
let receivedMessage = readerType.decode(bufferedMessage, 5); // It lives at 5 just after our schema ID
console.log(readerType.toString(receivedMessage.value));
```

Again, thank you for your help. Things are a little clearer now in regards to Avro and where this package fits in.

Kind regards,

Matt
