### ISSUE TITLE
Using forSchemaOptions  inside forSchema causes a duplicate type name error

### ISSUE THREAD

**Issue by alonisser** [mtth/avsc#294]
I'm using avsc wrapped by [schemaregistry](https://github.com/kafkajs/confluent-schema-registry)  Thanks for your hard word and good docs!

I'm trying to solve the long/bigint issue with the constraint I have only limited access directly to avsc. the wrapping library allows me to pass a ```forSchemaOptions``` configuration that is passed inside into an avsc wrapper and then invoked
```
 this.schema = Type.forSchema(schema, this.forSchemaOptions); (Type is from avsc)
```
I've found out that passing inside forSchemaOptions
{
registry: { long: longType } //Where longType is bigInt based long.__with as [the docs refer to](https://github.com/mtth/avsc/wiki/Advanced-usage#custom-long-types)
}

But I've encountered a peculiar problem.  if I pass a forSchemaOptions object with the registry or **even an empty object** ```{}``` without a registry

I get ONCE this error (the actual key is part of the schema auto generated by debezium/kafkaconnect)
```
"Error: duplicate type name: mongo_insights.zcdb_staging.dataitem.Key\n    at RecordType.Type (/home/alonisser/projects/zencity/zc-node-framework/node_modules/avsc/lib/types.js:107:17)\n    at new RecordType (/home/alonisser/projects/zencity/zc-node-framework/node_modules/avsc/lib/types.js:2099:8)\n    at /home/alonisser/projects/zencity/zc-node-framework/node_modules/avsc/lib/types.js:226:14\n    at Function.Type.forSchema (/home/alonisser/projects/zencity/zc-node-framework/node_modules/avsc/lib/types.js:227:7)\n
```
How can we work around this?

**Comment by alonisser** [comment]
Just to be clear if I don't pass any options at all - not an empty object - nothing at all, I don't get this error and get errors when trying to actually work with the long (which is a bit later I think)

**Comment by mtth** [comment]
Hi @alonisser. It looks like the issue comes from reusing options within the schema registry library. When an options object is passed in to `Type.forSchema` (even empty), its `registry` key will be populated with the newly instantiated types. This state persists between calls and will trigger a `duplicate type name` error when a later call tries to instantiate a type already registered.

Due to this behavior, it's best to avoid reusing options when possible. A simple solution is to allow users to provide an options factory: a function which returns options, called each time options need to be generated. Here, it sounds like this would require a change to the schema library, which I would encourage you to suggest.

In the meantime, I think you can work around the error by adding a `typeHook` to the options. This hook will intercept the type generation logic, checking first if a type with the same name is already registered and returning it directly if so. For example something like:

```js
// Hook to add as `typeHook` key to `Type.forSchema` options.
function typeHook(schema, opts) {
  let name = schema.name;
  if (!name) {
    return; // Not a named type, use default logic.
  }
  if (!~name.indexOf('.')) {
    // We need to qualify the type's name.
    const namespace = schema.namespace || opts.namespace;
    if (namespace) {
      name = `${namespace}.${name}`;
    }
  }
  // Return the type registered with the same name, if any.
  return opts.registry[name];
}
```

Let me know if this works for your use-case.

**Comment by alonisser** [comment]
Thanks for the reply @mtth I'm trying to work with the schemalibrary lib, but currently can't get traction there.
I've tried a direct typehook and failed to make it work, I'll try this and update

**Comment by alonisser** [comment]
Thanks, it worked!

**Comment by NicholasGWK** [comment]
Sorry to resurrect this, but will the same duplication problem happen if I'm trying to pass in logicalTypes as an option instead of registry? I feel like it might but I'm having trouble stepping through and seeing where "the state is persisted between calls" like you mentioned!

Thanks for any help :)

**Comment by mtth** [comment]
Hi @NicholasGWK. Assuming you are using the same underlying library, you will face the issue described above as soon as you specify options. The state is persisted in the options object itself: when non-`undefined`, it will gain a `registry` attribute which spans calls.

That being said, the `typeHook` snippet in https://github.com/mtth/avsc/issues/294#issuecomment-610176281 should allow you to work around it:

```js
const opts = {
  logicalTypes: {}, // Your logical types.
  typeHook, // The typehook from the comment above.
  // Any other options...
};
```
