### ISSUE TITLE
Question: serialization of EnumType

### ISSUE THREAD

**Issue by john-aws** [mtth/avsc#299]
This is a question, not an issue.

I'm using the file decoder API which streams each Avro record to me. As part of that process, I serialize the streamed objects to JSON. I've noticed that EnumType attributes serialize as follows:

    "gender" : { "person_gender_enum": "female" }

rather than:

    "gender" : "female"

Is this the expected behavior during serialization of enums? I'm wondering how to modify this behavior. I wasn't able to achieve it through a custom `avsc.types.EnumType.prototype._toJSON` override. Obviously, I would prefer not to have to iterate over the entire object, try to detect attributes that are of EnumType, and modify them so that I can JSON serialize the entire object in the way I want to.

Thanks in advance.

**Comment by mtth** [comment]
Hi @john-aws. I think this is happening because the field is nullable (has type `[null, person_gender_enum]`). The Avro specification enforces that [unions are JSON-encoded with the type as key](https://avro.apache.org/docs/current/spec.html#json_encoding). If you'd like to use a different representation, you could stick to the in-memory representation where unions are unwrapped when possible. [This thread](https://github.com/mtth/avsc/issues/231) has more context in case it's useful.
