### ISSUE TITLE
Questions about the future scope of this library

### ISSUE THREAD

**Issue by gabrielnau** [mtth/avsc#3]
Hi,

I was unfortunately working on a [fork of node-avro-io](https://github.com/Adikteev/node-avro-io) these days to make it work in the browser.

My primary goal was to support long numbers. The best solution I've found to do so is to use https://github.com/dcodeIO/Long.js. Would you (or did you) consider supporting long numbers, using `int64-native` for node and `long.js` (or another one) for the browser ?

At a higher level, is the work on this library supported by Linkedin ? If so I would expect this lib to become the de facto standard Avro javascript implementation.

Unrelated question, I'm curious about the use of Avro in the browser at Linkedin: is it already in production ? Are browser generated events used "as it" later on in Samza ?

Thanks

**Comment by mtth** [comment]
Hey!

Adding `long` support is definitely something I'm considering; I'm still thinking about how best to do so. Using an external library such as the ones you mention is an option, but I'd rather not tie `avsc` to any particular implementation (especially since it'll likely be two, one for node, and one for browsers). One other possibility would be to provide hooks (as an option to `avsc.parse`), letting you choose the best library for each use-case.

About your other questions, it's too early to tell :).

**Comment by mtth** [comment]
Created a more specific issue for `long` support: https://github.com/mtth/avsc/issues/4. Feel free to comment there if you have any suggestions or use-cases in mind.
