### ISSUE TITLE
support a more even file size distribution.

### ISSUE THREAD

**Issue by Gavin-TW** [mtth/avsc#302]
thanks for this great lib , and I face an issue if someone can give some help:

I follow this issue:https://github.com/mtth/avsc/issues/75

we pushing avro files to AWS every 10 MB and set an interval to check the buffer size (I copied buffer and judge the length)

but the interval block the e2e testing (after e2e ,app still hang on) , I think interval is also not suitable for the requirement(10 MB),it's has extra cost , so I want remove the interval and use writer/writeStream to padding multiple outputs just like :
input size:100MB
output size : file_001.avro(10MB) , ... , file_010.avro(10MB)；
for guaranteeing a more even file size distribution. 

if has some solutions or I missed some important options? 

would really appreciate it.

best  regard,
Gavin
@mtth   could you give me some solutions? 🙏

**Comment by Gavin-TW** [comment]
> thanks for this great lib , and I face an issue if someone can give some help:
> 
> I follow this issue:#75
> 
> we pushing avro files to AWS every 10 MB and set an interval to check the buffer size (I copied buffer and judge the length)
> 
> but the interval block the e2e testing (after e2e ,app still hang on) , I think interval is also not suitable for the requirement(10 MB),it's has extra cost , so I want remove the interval and use writer/writeStream to padding multiple outputs just like :
> input size:100MB
> output size : file_001.avro(10MB) , ... , file_010.avro(10MB)；
> for guaranteeing a more even file size distribution.
> 
> if has some solutions or I missed some important options?
> 
> would really appreciate it.
> 
> best regard,
> Gavin

@mtth

**Comment by mtth** [comment]
I'm not sure I understand the requirements. It sounds like your e2e testing is hanging because it's waiting for the next interval? You can solve this by listening to the `'finish'` event, similar to what the [minimal rotating encoder](https://github.com/mtth/avsc/issues/75#issuecomment-261960837) does and flushing early when the input stream ends. Otherwise, to achieve more regular file sizes, you could keep track of the sizes of the buffers emitted by the block encoder and trigger a rotation when it exceeds some threshold (instead of triggering on a timer). Note that the distribution of file sizes will depend on your block size since each file includes at least one block. Smaller blocks will give you more granular control on individual file sizes.

**Comment by Gavin-TW** [comment]
@mtth 
really appreciate for quickly response.

> Note that the distribution of file sizes will depend on your block size since each file includes at least one block. 
I set the block size is 16KB to do flushing  job . bigger block size may cost extra issue , also our input ratio is small , at least one day or more to reach 10MB. I copied the buffer and defined a counter for judging if the avro's container size is 10 MB , that is my solution . also works 😄 .
thanks
