### ISSUE TITLE
Saving buffer to file [Question]

### ISSUE THREAD

**Issue by orangold** [mtth/avsc#310]
Hi.
Using the example given in the library, I tried to write the encoded buffer into a file as following:
```
const avro = require('avsc');
var fs = require('fs');

const type = avro.Type.forSchema({
  type: 'record',
  fields: [
    {name: 'kind', type: {type: 'enum', symbols: ['CAT', 'DOG']}},
    {name: 'name', type: 'string'}
  ]
});
 
const buf = type.toBuffer({kind: 'CAT', name: 'Albert'}); // Encoded buffer.

var full_filename = "avro_data.avro";
fs.writeFile(full_filename, buf.toString(), function(err) {
    if(err) {
        return console.log(err);
    }
    console.log("The file was saved to '" + full_filename + "'");
});
```

However, trying to view this file in an Avro Viewer returns "Unable to properly parse JSON contents" or "Not a valid Avro file".
Am I missing something with the compression/writing to file here?
Thanks for your time.

**Comment by mtth** [comment]
Hi @orangold. Apologies for the delayed reply. I suspect the Avro viewer expects an [object container file](https://avro.apache.org/docs/current/spec.html#Object+Container+Files) rather than raw encodings. If so, you can create one with `avsc` using a [`BlockEncoder`](https://github.com/mtth/avsc/wiki/API#class-blockencoderschema-opts), for example:

```js
const encoder = avro.streams.createFileEncoder('path/to/file.avro', type);
encoder.write({kind: 'CAT', name: 'Albert'});
encoder.write({kind: 'CAT', name: 'Alice'}); // You can write more than one record.
encorde.end();
```

**Comment by orangold** [comment]
Hey. Thank you very much for your help :). Got it!
