### ISSUE TITLE
How do you properly combine multiple "records" into a single buffer?

### ISSUE THREAD

**Issue by Jaeiya** [mtth/avsc#313]
I've looked through the documentation, but it's not clear how to create a container of multiple records. Let's say we have a scheme like so:
```javascript
const userType = avro.Type.forSchema({
  name: 'User',
  type: 'record',
  fields: [
    {name: 'lastLoginDate', type: 'long'},
    {name: 'userId', type: 'int'},
    {name: 'email', type: 'string'},
  ]
});

```

How would one add multiple users data with that scheme, to a single buffer? I noticed under advanced usage, that you support extracting fields from a buffer (specifically user id in the example) using a resolver, but it's not clear how to actually save multiple users data within the buffer.

It would also be nice to know how to edit information in a buffer, once it's been pulled out. Whether that means saving the entire schema or somehow transplanting the data back in with a method I'm not aware of.

I apologize if this is a very amateurish question; this happens to be my first foray into working with binary data (buffers) within any programming environment.

**Comment by mtth** [comment]
Hi @Jaeiya and welcome to the world of binary data!

> How would one add multiple users data with that scheme, to a single buffer? 

There are a couple popular options, each better suited for different use-cases. For example:

+ Wrapping your type in a wrapping type and encoding it directly:

  ```javascript
  const arrayType = avro.Type.forSchema({type: 'array', items: userType});
  const buf = arrayType.toBuffer([user1, user2, /* ... */]);
  ```

  Instead of the array, you can also use a map or another wrapper to provide more information. This approach is useful if you don't have too many values and consumers of the buffers already have the schema to decode them.

+ Using a [`BlockEncoder`](https://github.com/mtth/avsc/wiki/API#class-blockencoderschema-opts) to assemble your values into a container object:

  ```javascript
  const encoder = new avro.streams.BlockEncoder(userType);
  encoder.write(user1);
  encoder.write(user2);
  // ...
  encoder.end();
  ```

  The encoder is a standard [duplex stream](https://nodejs.org/api/stream.html#stream_duplex_and_transform_streams) which encodes the values and makes their schema available to later consumers. This approach is typically used when you have many values (possibly not all fitting in memory at once) and you want the binary data to be self-documenting.

> It would also be nice to know how to edit information in a buffer, once it's been pulled out.

Encoded buffers are best thought of as immutable and should almost never be edited directly due to the specificities of the encoding (the same which allow for the compact representation). Serialization roundtrips are fast enough that most use-cases can simply decode, edit , then reencode buffers.

I hope this helps. Please let me know if anything is still unclear or you have further questions.

**Comment by Jaeiya** [comment]
Thank you very much for that explanation, that helped a lot!

I decided to go with wrapping my type in a wrapping type. I found a more advanced type schema from another article that fit my use-case, but I was wondering if you could look it over and tell me if there's a more compact way to represent it?

I had originally wanted to simply store my objects like this in JSON:
```
[
 	{ 
		questions: string[], 
		answer: string, 
		hashes: number[], 
		dateCreated: number, 
		dateEdited: number 
 	},
	...
]
```
And programmatically I would search through them using the hashes which are unique. So as you can see I don't need them to have a name, but obviously the schema appears to need them to be in a named parent object and for the children to also have names.

So using the example I found online from another article, I came up with this schema, which does work. I'm just curious if there's a more succinct way to write this for my use-case. I really appreciate you taking the time to offer me advice! 😄 

```typescript
export const replySchema = avro.Type.forSchema({
  name: 'Replies',
  type: 'record',
  fields: [
    {
      name: 'replies',
      type: [
        { type: 'array', items: [
          {
            type: 'record',
            name: 'Reply',
            fields: [
              { name: 'questions', type: { type: 'array', items: 'string'}},
              { name: 'answer', type: 'string' },
              { name: 'hashes', type: { type: 'array', items: 'long'}},
              { name: 'dateCreated', type: 'long' },
              { name: 'dateEdited', type: 'long' },
            ]
          }
        ]}
      ]
    }
  ]
});
```

**Comment by mtth** [comment]
Your schema looks good. You could omit the outer `record` type if you'd like to trim it down, but it is sometimes convenient to have a named object for logs so keeping it is a fine choice too. (Fun Avro fact: the wrapping record is "free" storage-wise, the serialization is identical with and without it.)

**Comment by Jaeiya** [comment]
Thank you for that tip, I was able to reduce it to this:
```javascript
{
  name: 'replies',
  type: 'array', items: [
      {
        type: 'record',
        name: 'Reply',
        fields: [
          { name: 'questions', type: { type: 'array', items: 'string'}},
          { name: 'answer', type: 'string' },
          { name: 'hashes', type: { type: 'array', items: 'long'}},
          { name: 'dateCreated', type: 'long' },
          { name: 'dateEdited', type: 'long' },
        ]
      }
    ]
}
```
I suppose if I have any more questions or concerns, I'll just comment on this issue. Thanks again for all your help 👍

**Comment by deleuterio** [comment]
It's a good first issue!
