### ISSUE TITLE
How to incrementally decode array items

### ISSUE THREAD

**Issue by devdoshi** [mtth/avsc#331]
I have a schema like the following:
```json
{
  "type": "record",
  "name": "batch",
  "fields": [
    {
      "name": "groupingIdentifiers",
      "type": {
        "type": "record",
        "name": "GroupingIdentifiers",
        "fields": [
          {
            "name": "category1Id",
            "type": "string"
          },
          {
            "name": "category2Id",
            "type": "string"
          }
        ]
      }
    },
    {
      "name": "batchItems",
      "type": {
        "type": "array",
        "items": {
          "type": "record",
          "name": "BatchItem",
          "fields": [
            {
              "name": "uuid",
              "type": "string"
            },
            {
              "name": "metadata",
              "type": "string"
            },
          ]
        }
      }
    }
  ]
}
```

Let's say there are a lot of `batchItems` and `batchItems[i].metadata` is costly to decode, and we only want to decode it if e.g. `batchItems[i].uuid` matches some value. Given a fileEncoded `batch`, is it possible to extract the batchItems as a Buffer? Then I would be able to use the schema evolution/resolver features to filter the batchItems and only then decode the metadata

**Comment by mtth** [comment]
Hi @devdoshi. There is currently no good way to incrementally decode array elements in the general case. Partial decoding as described [here](https://github.com/mtth/avsc/wiki/Advanced-usage#schema-evolution) will work but has limited benefits for this use-case since the schema applies to all elements in the array: it's not possible to selectively decode select a few. It will be beneficial if there are a significant number of arrays with no matches at all.

Note that in your specific example, `string` and `bytes` Avro types are interchangeable so you would be able to retrieve `metadata` as a `Buffer` by using a tweaked schema and creating a resolver as explained in the link above. I expect any gains would be small though since string parsing is relatively cheap (significant gains from partial decoding usually come from skipping large arrays or nested data).

**Comment by devdoshi** [comment]
That's what I thought :( Luckily I was able to change the schema to just be the `BatchItem` written multiple times to the fileEncoder and used the partial decoding approach. Thanks for the tip about strings and bytes, but in reality the `metadata` schema is a record I simplified for the example. I'll figure out something else for the `groupingIdentifiers` later.

Thanks for the great library and quick reply!
