### ISSUE TITLE
Issue with empty string in timestamp-millis logical type

### ISSUE THREAD

**Issue by kri5t** [mtth/avsc#360]
I am trying to use this library to parse some information from Hubspot. Unfortunately they sometimes send back date values as `empty strings` instead of `null`.

I have created a parser based of the logical type in your readme. I am basically just trying to return `null` when we encounter empty string in place of a `datetime`. 

I am unsure if this is even allowed - but it seems to be working when the attribute is `null` or `undefined`.

The example here should demonstrate the issue:
``` ts
import * as avro from 'avsc';

class DateTypeLogicalType extends avro.types.LogicalType {
  _fromValue(val: number | null | undefined) {
    if (val === null || val === undefined) {
      return null;
    }
    const transform = new Date(val);
    return transform;
  }
  _toValue(date: Date | string | null | undefined) {
    if (date === null || date === undefined || date === '') {
      return null;
    }
    const transform = date instanceof Date ? +date : new Date(date).getTime();
    return transform;
  }
  _resolve(type: avro.Type) {
    if (avro.Type.isType(type, 'long', 'string', 'logical:timestamp-millis')) {
      return this._fromValue;
    }
  }
}

const schemaAsJson: any = {
  name: 'plans',
  type: 'record',
  fields: [
    {
      name: 'test',
      type: ['null', { type: 'long', logicalType: 'timestamp-millis' }],
      default: null,
    },
  ],
};

const aSchema = avro.Type.forSchema(schemaAsJson, {
  wrapUnions: 'auto',
  logicalTypes: {
    'timestamp-millis': DateTypeLogicalType,
  },
});

const object = { test: '' };

aSchema.isValid(object, {
  errorHook: (path, val, type) => {
    console.log('path:', path);
    console.log('val:', val);
  },
  noUndeclaredFields: false,
});
```

**Comment by mtth** [comment]
Hi @kri5t. The issue is that `DateTypeLogicalType` decorates a `long` and must therefore only return longs from `_toValue` (not `undefined` or `null`). Here are a few alternatives which would work:

1. Pre-processing the records, replacing the empty strings with nulls.
2. Using another logical type to decorate the `null` side of the branch, which accepts empty strings and transforms them to nulls. More code but self-contained processing logic.
3. Decorating the entire union with a logical type. Good for reuse but highest complexity (see [here](https://github.com/mtth/avsc/issues/69#issuecomment-250661348) for an example).
4. Using a logical type on a wrapper type, which performs the same operation as 1 and possibly also the date transformation. Cleanest schema but difficult to generalize.

My recommendation would be 1, simpler to maintain in most cases.

**Comment by kri5t** [comment]
@mtth 
That makes a lot of sense. Thanks so much for the quick answer. We will assess the options and go with one of them. 

And also thanks for all the work you have done with this library. Really helpful when working with Avro in Node. 👍
