### ISSUE TITLE
Deviation from spec - reader schema with different namespaces

### ISSUE THREAD

**Issue by ivank** [mtth/avsc#361]
When doing reader schema (createResolver), avsc considers the full name (with namespace) of a field in a record to do the matching, however the latest spec says that it should not use the namespace for those resolutions.

https://avro.apache.org/docs/current/spec.html

In "Schema Resolution" section:

>It is an error if the two schemas do not match.
>To match, one of the following must hold:
> * both schemas are records with the same (unqualified) name
> * **if both are records:**
>   * schemas for fields with the same name in both records are resolved recursively.

Don't know java really but when reading the tests for the java implementation, you can see this:

https://github.com/apache/avro/blob/4a5e4a686e55882d48c527328502700c765f1772/lang/java/avro/src/test/java/org/apache/avro/TestSchemaCompatibility.java#L316-L318

https://github.com/apache/avro/blob/4a5e4a686e55882d48c527328502700c765f1772/lang/java/avro/src/test/java/org/apache/avro/TestSchemas.java#L106-L109

https://github.com/apache/avro/blob/4a5e4a686e55882d48c527328502700c765f1772/lang/java/avro/src/test/java/org/apache/avro/TestSchemas.java#L133-L139

Which seems to indicate that if we're trying to compare two records with the same schema, but different namespaces, they should match.

I've tried to duplicate this with `avsc`, and we get an error: 

> Error: cannot read {"type":"array","items":"ns2.InnerRecord1"} as ["null",{"type":"array","items":"ns1.InnerRecord1"}]

```typescript
import { Schema, Type } from 'avsc';

const nsInnerRecord1: Schema = {
  type: 'record',
  name: 'InnerRecord1',
  namespace: 'ns1',
  fields: [{ name: 'a', type: 'int' }],
};

const nsInnerRecord2: Schema = {
  type: 'record',
  name: 'InnerRecord1',
  namespace: 'ns2',
  fields: [{ name: 'a', type: 'int' }],
};

const nsRecord1: Schema = {
  type: 'record',
  name: 'Record1',
  fields: [{ name: 'f1', type: ['null', { type: 'array', items: nsInnerRecord1 }] }],
};

const nsRecord2: Schema = {
  type: 'record',
  name: 'Record1',
  fields: [{ name: 'f1', type: ['null', { type: 'array', items: nsInnerRecord2 }] }],
};

const reader = Type.forSchema(nsRecord1);
const writer = Type.forSchema(nsRecord2);

const resolver = reader.createResolver(writer);

const writerVal = { f1: [{ a: 1 }, { a: 2 }] };

const buf = writer.toBuffer(writerVal);

const readerVal = reader.fromBuffer(buf, resolver);

console.log(writerVal, readerVal);
```

This functionality is important for the kafka schema evolution work that our company is engaged in, apparently it was working fine with java (Scala) consumers but broke with js ones.

We would be happy to try to patch this ourselves if you don't have time, as its rather important for us, but might need for you to point out where we need to start.

**Comment by mtth** [comment]
Interesting, thanks for reporting. It looks like the wording was added to the spec in `1.9.1` to clarify a common inconsistency ([context](https://issues.apache.org/jira/browse/AVRO-2400)). I am OK adding a `createResolver` option to support this and would be happy to review a PR implementing it. The default should remain strict: relaxed name checking is more likely to lead to hard to debug issues (it was chosen to preserve backwards compatibility with the Java implementation).

Note that this change will not affect how union branches are decoded (for example in the [issue linked above](https://github.com/ovotech/castle/issues/89)). These must continue to use the fully qualified name, otherwise it would not be possible to union multiple types with the same name and different namespace together. Schema resolution does not mean in-memory representations are interchangeable, it means an encoded value can be decoded into another compatible in-memory representation.

**Comment by mtth** [comment]
`5.7.3` introduced a new [`ignoreNamespaces` option](https://github.com/mtth/avsc/wiki/API#typecreateresolverwritertype-opts) to support the above behavior.
