### ISSUE TITLE
Can't handshake when I connect to Avro java 

### ISSUE THREAD

**Issue by crazybear** [mtth/avsc#43]
Could I use avsc connect to server what use  java avro?
I have try a lot of way but can't **handshake**?

**Comment by mtth** [comment]
You definitely can.

In case it helps, I just created a small RPC sample gist (JavaScript client and Java server over HTTP) you can take a look at: https://gist.github.com/mtth/e94e3bb95671143d7251.

Which transport are you using?

**Comment by crazybear** [comment]
thank u！

I had use TCP by net module of nodejs

I will try it over Http

**Comment by crazybear** [comment]
By the way
Can i use TCP？

**Comment by crazybear** [comment]
By the way can i use Netty?

**Comment by mtth** [comment]
> I know what's wrong my Message Framing is different from Java server

Right, Avro's Java `NettyTransportCodec` is using a custom transport format. Since it's different from the one defined in the specification, supporting it will require writing the corresponding decoder/encoder. Unfortunately it's not that straightforward to do, especially since it encodes request and response identifiers (rather than using the `meta` field already available in each Avro message header).
