### ISSUE TITLE
optionally throw Exception when checking isValid

### ISSUE THREAD

**Issue by adrian-sgn** [mtth/avsc#5]
It's difficult to tell why an object may fail schema validation at runtime

it would be great if avsc could have `isValid()` optionally throw an Exception which would provide detail about which field failed the validation and perhaps why.

An example interface:

```
var avroSchema = avsc.parse(mySchema);
avroSchema.isValid(myObj, {throw:true});
```

or, ala node-avro-io:

```
var avroSchema = avsc.parse(mySchema);
avroSchema.isValidAndThrow(myObj);
```

**Comment by mtth** [comment]
That's a great point. Agreed, it's currently difficult to trace validation errors. I'll work on improving this.

**Comment by mtth** [comment]
@adrian-sgn - since `2.3.0` (just released) [`isValid`](https://github.com/mtth/avsc/wiki/API#typeisvalidobj-opts) exposes an `errorHook` to help debug validation errors. For example, you can use it to implement the `assertValid` function you suggest:
```javascript
function assertValid(type, obj) {
  return type.isValid(obj, {errorHook: function (obj, type, path) {
    throw new Error('invalid ' + path.join());
  }});
}
```

Or even - if you'd like to get all invalid paths in a single call - you can too:
```javascript
function getInvalidPaths(type, obj) {
  var paths = [];
  type.isValid(obj, {errorHook: function (obj, type, path) { paths.push(path.join()); }});
  return paths;
}
```
The invalid value and expected type are also available (as `obj` and `type` in the callback, unused in the examples above). More information in the [API documentation](https://github.com/mtth/avsc/wiki/API#typeisvalidobj-opts)!
