### ISSUE TITLE
ambiguous unwrapped union

### ISSUE THREAD

**Issue by Osmosis311** [mtth/avsc#52]
I get an error that says "ambiguous unwrapped union" when I try process one of my company's Avro log files.

Is there any way to somehow support this?

Thanks!

**Comment by mtth** [comment]
Yes, you can use [`parse`](https://github.com/mtth/avsc/wiki/API#parseschema-opts)'s `wrapUnions` option. For example:

```javascript
var type = avro.parse(['int', 'double'], {wrapUnions: true});
```

This will change the decoded representation of the union's branches to include their type: this is required to not risk corrupting data since Avro types don't map perfectly to JavaScript types. You can read more about which unions are ambiguous and why on [the API page](https://github.com/mtth/avsc/wiki/API#class-unwrappeduniontypeattrs-opts). The issues referenced in https://github.com/mtth/avsc/issues/42 might also be helpful.

So, continuing the above example:

```javascript
type.isValid(12); // false
type.isValid({int: 12}); // true
type.isValid({double: 48}); // true
```

Finally, the `wrapUnions` option will apply to all unions in your schema. If you wish to wrap only certain unions, you can do so by instantiating the unions directly using `parse`'s `typeHook` option instead (perhaps even implementing your own union type).

Does this answer your question?

**Comment by Osmosis311** [comment]
Thanks for the fast response!

I'm not sure this does answer the question, or, more specifically, I need some more help.

I have an Avro data file which contains both data and schema.  I don't know the schema "ahead of time."  Is there a way to pass the wrapUnions option to the file decoder somehow?  Or, is the only way to use that option is if I know the schema before trying to process a data file?

Thanks.

**Comment by mtth** [comment]
I see. Then you would still use the same option, applying it via [`BlockDecoder`](https://github.com/mtth/avsc/wiki/API#class-blockdecoderopts)'s `parseHook` option. For example, assuming you're reading a local file:

```javascript
// Hook called when the schema inside a file gets parsed.
function hook(attrs) { return avro.parse(attrs, {wrapUnions: true}); }

// A readable stream where all unions are wrapped.
var readable = avro.createFileDecoder('data.avro', {parseHook: hook});
```

**Comment by Osmosis311** [comment]
That worked!  Thank you very, very much!!!

**Comment by Osmosis311** [comment]
@mtth is there a way to use the code above, but from a buffer instead of from a file?  Can't seem to figure that out....

Thanks!

**Comment by mtth** [comment]
Do you mean decoding a buffer with a single encoded value, decoding a buffer with an entire container file inside of it, something else? If the first, the example in my first reply above should work, if the second you can "wrap" the buffer in a readable stream and pipe it to a `BlockDecoder`.

**Comment by Osmosis311** [comment]
It's a buffer containing a group of values (e.g. multiple "sets" of data).

Can you give me an example of that syntax?  Is it something like:

`var readable = avro.createBlockDecoder(buffer_value, {parseHook: hook});`?

Thanks!

**Comment by Osmosis311** [comment]
I got it!  Thanks!
