### ISSUE TITLE
Combined schema and encoded message

### ISSUE THREAD

**Issue by SirCameronMcAlpine** [mtth/avsc#54]
Hi,

Thanks for creating this module :)

I would like to know if it's possible to combine the schema and the encoded data into one message to be sent over kafka.
I understand this is not ideal, but it's how we're using this while in a testing/sketch phase.

Thanks in advance for your help,
Cameron

**Comment by mtth** [comment]
You can definitely combine the schema and encoded data into a single message. Since there is no standard way of doing so, it's up to you to decide which convention to use. It could be as simple as prefixing each message with the schema's full JSON representation.

A few things to keep in mind:

+ Since the overhead of including the schema can be pretty high, you'll want to look into batching your messages (e.g. sending an array of payloads rather than a single one). You can find more context about this [here](http://stackoverflow.com/q/37440658/1062617).
+ Parsing a schema into a `type` is an expensive operation, so you might want to cache schemas when decoding. You might even want to push this a bit further and reference schemas by IDs as described in https://github.com/mtth/avsc/issues/22.

**Comment by SirCameronMcAlpine** [comment]
Thanks @mtth. I've decided against this because it negates the speed of avro.
Thanks for your help, though!

I'll close this :)
