### ISSUE TITLE
Add clarity to UnwrappedUnionType errors?

### ISSUE THREAD

**Issue by gregsadetsky** [mtth/avsc#57]
The Avro schema I'm using contains a field whose type is an array of possible types. See below for a simplified version:

```javascript
var type = avro.parse({
  "type": "record",
  "fields": [
    {
      "name": "myFieldName",
      "type": ["null", "long"]
    }
  ]
});

var buf = type.toBuffer({
  myFieldName: '' // incorrectly passing string
});
```

I was passing the wrong type (a string instead of null or a long) and avsc threw the following error:

```
Uncaught Error: invalid ["null","long"]: ""
```

Although useful as the empty string value I was passing was output, I still had trouble finding which field was incorrectly passed (as I am passing many other fields as well, some that also have `["null", "long"]` types).

I was wondering if there was a way to add the field's name ("myFieldName") in `throwInvalidError`'s error message? I saw that the UnwrappedUnionType instance had an empty `_name` (since this is a "natural" union type..?), so I didn't know how to proceed to extract the field's name from which this type instance was created.

Thanks!

**Comment by mtth** [comment]
Thanks for the clear example!

[`type.isValid`](https://github.com/mtth/avsc/wiki/API#typeisvalidval-opts) provides this functionality. In particular, the gists mentioned in the documentation should point you in the right direction. For example, the [assert.js gist](https://gist.github.com/mtth/fe006b5b001beeaed95f#file-assert-js) already includes the invalid field's name in its error messages (the expected type is also available in the `errorHook` if you'd like to include it as well):

```javascript
assertValid(type, ﻿{myFieldName: ''}); // Error: invalid myFieldName: ""
```

Does this satisfy your use-case?

Making this information available to `throwInvalidError` would be very expensive (likely resulting in an order of magnitude slowdown for encoding) and probably isn't worth the hit. It also isn't possible to use a type's `_name` here since types are meant to be independent of where they are used (a single type might be shared by multiple fields for example).

**Comment by gregsadetsky** [comment]
Thank you very much, that makes perfect sense! I'll know to use assertValid next time to figure out what the problem is. (Also it makes sense that types are shared -- thanks for the clear explanation!)
