### ISSUE TITLE
Enable type inference for ambiguous unwrapped union

### ISSUE THREAD

**Issue by jcare44** [mtth/avsc#69]
Rigth now, when parsing a schema that has more than one `number`-like type (ex: `int`, `long`, `float`, `double`) in union, the parsing of the type fails in unwrapped mode.

Is there currently a way to work around it ? Wouldn't it be better to offer type inference in those ambiguous cases ? (`avsc.infer()` seems close to the solution, for `number`-like types at least)

I think the solution of the wrapped mode is great when you create data to be serialized. 
But, When you want to serialize existing data in a generic way, wrapped mode is kind of painfull since it force you to search for unions in your schema in order to wrap them (with their known type or through type inference) in your data.

Thank you for your time :)

**Comment by mtth** [comment]
If you have more than one number type inside a union, you're not guaranteed to be able to keep the right type if you use a JavaScript `Number` to represent it (i.e. accurate type inference is not possible). This is a problem since it means serializing the same value could lead to a different encoding than in other implementations (e.g. ones in other languages). 

If you are OK relaxing this assumption, or if you can use properties of your data to infer the type, there are indeed ways to work around it by providing a custom implementation for unions. For example, you could implement a logical type with your own inference logic. [`OptionalType`](https://gist.github.com/mtth/1aec40375fbcb077aee7#file-optional-js) is an example of this; a more generic one could look as follows:

```javascript
const avro = require('avsc');

/** A union type which lets you control how branch inference is done. */
class CustomUnionType extends avro.types.LogicalType {

  _inferType(val) {
    // Implement your own custom inference logic here. The underlying union is
    // available as `this.getUnderlyingType()` (to access the array of possible
    // branches for example). This sample implementation will use the first
    // type for which the value is valid.
    for (const type of this.getUnderlyingType().getTypes()) {
      if (type.isValid(val)) {
        return type;
      }
    }
    throw new Error(`invalid value: ${val}`);
  }

  _toValue(any) {
    // Wrap the value using the inferred type.
    return {[this._inferType(any).getName(true)]: any};
  }

  _fromValue(val) {
    // Unwrap the value (simple case).
    return val === null ? null : val[Object.keys(val)[0]];
  }
}
```

Here's an example of how you might use it:

```javascript
/** Generate a type hook to apply the custom logical type above to all unions. */
function createTypeHook() {
  const visited = [];
  return (attrs, opts) => {
    if (attrs instanceof Array && !~visited.indexOf(attrs)) {
      visited.push(attrs);
      return new CustomUnionType(attrs, opts);
    }
  };
}

// A sample type to apply our custom union:
const type = avro.parse(
  ['null', 'int', 'float'],
  {typeHook: createTypeHook(), wrapUnions: true});

// We can finally check that it accepts unwrapped values:
console.log(type.isValid(null)); // true
console.log(type.isValid(1)); // true
console.log(type.isValid(1.4)); // true
console.log(type.isValid('not this one')); //false
```

Let me know if anything is unclear. The [logical type documentation](https://github.com/mtth/avsc/wiki/Advanced-usage#logical-types) might also be helpful.

**Comment by jcare44** [comment]
Great ! That's just what I've been looking for !

Thank you :)

**Comment by mtth** [comment]
Awesome :).
