### ISSUE TITLE
stream encoder / decoder

### ISSUE THREAD

**Issue by pgte** [mtth/avsc#74]
I'm struggling with finding a way to create an encoder and a decoder duplex streams.
As a reference, I'm used to things like [`msgpack.encoder()`](https://github.com/mcollina/msgpack5#encoder) and [`msgpack.decoder()`](https://github.com/mcollina/msgpack5#decoder), that return me duplex streams I can pipe to and from other streams like this:

```js
const encoder = msgpack.encoder()
encoder.pipe(conn)

encoder.write(...
```

```js
const decoder = msgpack.decoder()
conn.pipe(decoder)
decoder.on('data', function(d) {
  console.log(d)
})
```

Does avsc provide something similar?

**Comment by mtth** [comment]
`avsc` provides a [`RawDecoder`](https://github.com/mtth/avsc/wiki/API#class-rawdecoderschema-opts) and [`RawEncoder`](https://github.com/mtth/avsc/wiki/API#class-rawencoderschema-opts) which match what you are looking for. For example:

```javascript
const avro = require('avsc');

// We'll be encoding integers here.
const encoder = new avro.streams.RawEncoder('int');
const decoder = new avro.streams.RawDecoder('int');

// Sample usage which encodes, decodes, and prints.
encoder
  .pipe(decoder)
  .on('data', (val) => console.log(val));

// This will output 12, 3, and 4.
encoder.write(12);
encoder.write(3);
encoder.end(4);
```

Using these is usually a code-smell though, what are you trying to do? For offline use-cases, block [decoders](https://github.com/mtth/avsc/wiki/API#class-blockdecoderopts) and [encoders](https://github.com/mtth/avsc/wiki/API#class-blockencoderschema-opts) are typically more appropriate (providing compression, schema embedding, consistency checks). And online, [RPC](https://github.com/mtth/avsc/wiki/Advanced-usage#remote-procedure-calls) automatically takes care of decoding and encoding.

**Comment by pgte** [comment]
Thanks for your reply.
Regarding your example, it only works if I end the encoder. If I keep the encoder open, the decoder gets no data.

**Comment by mtth** [comment]
That's most likely because [writes are batched](https://github.com/mtth/avsc/wiki/API#class-rawencoderschema-opts). You can lower the batch size to have data appear faster on the readable side (at the cost of slightly lower throughput):

```javascript
const encoder = new avro.streams.RawEncoder('int', {batchSize: 1});
```

It's also relatively straightforward to implement to implement a custom encoder that doesn't perform any batching:

```javascript
const Transform = require('stream').Transform;

/** Encoder which will emit values as soon as they are written. */
class Encoder extends Transform {
  constructor(schema) {
    super({writableObjectMode: true});
    this.type = avro.parse(schema);
  }
  _transform(data, encoding, cb) {
    cb(null, this.type.toBuffer(data));
  }
}
```

**Comment by pgte** [comment]
@mtth thanks, understood.

BTW, I'd be interested in knowing why you think a stream would e a code smell.
In my case I want a stream of records that always conform to the same schema, and I don't want RPC semantics. Do you see anything wrong with this?

(thanks so much for your help so far)

**Comment by mtth** [comment]
There are cases where using these decoder/encoders is appropriate. It sounds like yours might be, thought it's hard to say without knowing more about the context. Typically these are cases where the streams are either short-lived or have low latency requirements and don't fit neatly inside other RPCs.

Closing this since you got the raw streams working. Feel free to reopen if you have any more issues or questions.
