### ISSUE TITLE
How to retrieve LogicalType after parsing?

### ISSUE THREAD

**Issue by mll75** [mtth/avsc#80]
Hello,

I try to load an avro file (using createFileDecoder).
The schema contains a field of LogicalType 'timestamp-millis'.
I read the schema using the event metadata, but when I use type.getSchema(), the logicalType is not returned, only the primitive type "long".

I tried to write a simpler example showing my problem, it is like this:

```
var avro = require('avsc');

const type = avro.parse({
  name: 'Test',
  type: 'record',
  fields: [
    {name: 'name', type: 'string'},
    {name: 'date', type: {type: 'long', logicalType : 'timestamp-millis'}}
  ]
});

var schema = type.getSchema({exportAttrs: true});
console.log(schema);
```
console.log shows:
`{"name":"Test","type":"record","fields":[{"name":"name","type":"string"},{"name":"date","type":"long"}]}
`
where the logical type is not returned.

If I did not wrote a mistake, is it an expected behaviour?
Is there a possibility to have this logicalType information like it is saved in the header of my Avro file?

thanks for this great work!

**Comment by mtth** [comment]
Hey, it depends. If you are trying to extract a schema from an Avro file as-is, the simplest is to listen to the `'metadata'` event and read it from there:

```javascript
avro.createFileDecoder('events.avro')
  .on('metadata', function (type, codec, headers) {
    var schema = JSON.parse(headers.meta['avro.schema'].toString());
    // `schema` will contain the schema exactly as written to the file.
  });
```

Otherwise, since `type.getSchema()` builds a schema from the type, it won't include attributes that the type is unaware of. In your example above, your options are:

+ Keeping track of the object you pass to `avro.parse` separately (simplest option, supports arbitrary metadata in the schema).
+ Passing in a `timestamp-ms` logical type to `avro.parse` (optionally implementing its [`_export`](https://github.com/mtth/avsc/wiki/API#type_exportattrs) if you'd like to export other attributes than just the logical type's name).

Does this make sense?

**Comment by mll75** [comment]
Thanks Matthieu,

The first solution (reading the schema directly from file headers) works perfectly!
