### ISSUE TITLE
deserialize float value 6.1

### ISSUE THREAD

**Issue by hammerlabs** [mtth/avsc#94]
I wanted to test this library for a project I'm using, but when I pasted in some of the sample code you provided in the wiki, I got unexpected results. Here's the code I used:

```
const type = avro.Type.forValue([1, 4.5, 8]);
// We can now encode or any array of floats using this type:
const buf = type.toBuffer([4, 6.1]);
const val = type.fromBuffer(buf); // [4, 6.1]
console.log(val); 
```

In the console, I got [4, 6.099999904632568] instead of [4, 6.1]. I am hoping to use this in the browser and tested using Chrome 56.

**Comment by mtth** [comment]
The default type for numbers when using `Type.forValue` is `float` which is more compact than `double` but can cause some precision loss (see https://github.com/mtth/avsc/issues/91 for a bit more context). Here are a couple options:

+ Use `Type.forSchema`'s `valueHook` option to force all numbers to be encoded as `double`s:

  ```javascript
  function valueHook(val, opts) {
    return typeof val == 'number' ? Type.forSchema('double', opts) : undefined;
  }
  const type = avro.Type.forValue([1, 4.5, 8], {valueHook}); // Typed as array of doubles.
  ```

+ Define your schema explicitly and use `Type.forSchema` instead of relying on `Type.forValue`. This would give you the most control on the encoding (recommended especially if precision issues are relevant for your project). For your above example, the schema would be something like `{"type": "array", "items": "double"}`.
+ Use the generated schema as-is; the precision loss is likely very small for reasonably sized numbers.

Does either sound workable for you?

**Comment by hammerlabs** [comment]
Thanks for the explanation!

This yields the expected results and isn't a lot of extra trouble:

```
const type = avro.Type.forSchema({"type": "array", "items": "double"});
// We can now encode or any array of floats using this type:
const buf = type.toBuffer([4, 6.1]);
const val = type.fromBuffer(buf); // [4, 6.1]
```

Thanks!
