### ISSUE TITLE
type clone() with wrapUnions does not work?

### ISSUE THREAD

**Issue by aidanbon** [mtth/avsc#98]
Following the discussion at https://github.com/mtth/avsc/issues/16 and cut and paste the sample code mentioned in the stackoverflow (see below), I expect the cloned value is in wrapped format, but turns out it is still unwrapped?! Do I miss something?

Here's the cut-n-paste from the stackoverflow discussion:
http://stackoverflow.com/questions/33236284/how-to-convert-a-json-object-into-avro-object-if-avro-schema-contains-union-in-i/33622239#33622239

```
var avsc = require('avsc');

var type =  avsc.parse({
  "type":"record",
  "name":"DataFlowEntity",
  "namespace":"org.sdf.manage.commons.server",
  "fields": [
    {"name":"dataTypeGroupName","type":["null","string"]},
    {"name":"dataTypeName","type":"string"},
    {"name":"dataSchemaVersion","type":"string"}
  ]
});

var invalidRecord = {
  "dataTypeGroupName": "dg_1",
  "dataTypeName": "dt_1",
  "dataSchemaVersion": "1"
};

var validRecord = type.clone(invalidRecord, {wrapUnions: true});
console.log(validRecord)
```

Expected cloned value as wrapped:
```
{
  "dataTypeGroupName":{"string":"dg_1"},
  "dataTypeName":"dt_1",
  "dataSchemaVersion":"1"
}
```

But the above code returns unwrapped result?!
```
{
  "dataTypeGroupName":"dg_1",
  "dataTypeName":"dt_1",
  "dataSchemaVersion":"1"
}
```

**Comment by mtth** [comment]
It's because `5.0` changed the default wrapping behavior when parsing types: unions are now only represented wrapped where needed.

[`clone`](https://github.com/mtth/avsc/wiki/API#typecloneval-opts)'s `wrapUnions` option requires the underlying union to be wrapped, otherwise it might lead to invalid values, which isn't the case above since `["null", "string"]` isn't ambiguous (take a look at the [union types](https://github.com/mtth/avsc/wiki/API#class-unwrappeduniontypeschema-opts) for a bit more information).

You can still force wrapping by explicitly setting `parse`'s `wrapUnions` option though; here's a type that'll make your example work as expected:

```javascript
var type =  avsc.parse({
  "type":"record",
  "name":"DataFlowEntity",
  "namespace":"org.sdf.manage.commons.server",
  "fields": [
    {"name":"dataTypeGroupName","type":["null","string"]},
    {"name":"dataTypeName","type":"string"},
    {"name":"dataSchemaVersion","type":"string"}
  ]
}, {wrapUnions: true});
```

I updated the example on Stack Overflow to reflect the change. Thanks for bringing it up!
